"""empty message

Revision ID: 1ca961405365
Revises: faa482c1e292
Create Date: 2024-07-03 12:35:48.497651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca961405365'
down_revision = 'faa482c1e292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
